{
  "hash": "5d24291d393d0794eb8579c1e8a0bb15",
  "result": {
    "markdown": "---\ntitle: \"Randomized Controlled Trials\"\nauthor: \"Yazan Dabbas\"\ndate: \"12/19/2023\"\nformat: \n    html:\n      code-line-numbers: true\n      df-print: paged\n---\n\n::: {.cell hash='06_rct_cache/html/unnamed-chunk-1_91e534107a69814e1e35b0c9de5873ac'}\n\n```{.r .cell-code}\n# Load required libraries\nlibrary(ggplot2)\n```\n:::\n\n::: {.cell hash='06_rct_cache/html/unnamed-chunk-2_096ab996e04ae6c1a4bf70db1182e46f'}\n\n```{.r .cell-code}\n# Load the Data\ndf <- readRDS(\"C:/Master Degree/Core Qualification_Compulsory Courses/Business/Causal_Data_Science/Data/Causal_Data_Science_Data//abtest_online.rds\")\n\n# Be familiar with the data\nhead(df)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"ip\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"chatbot\"],\"name\":[2],\"type\":[\"lgl\"],\"align\":[\"right\"]},{\"label\":[\"previous_visit\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"mobile_device\"],\"name\":[4],\"type\":[\"lgl\"],\"align\":[\"right\"]},{\"label\":[\"purchase\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"purchase_amount\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"161.88.211.70\",\"2\":\"TRUE\",\"3\":\"0\",\"4\":\"FALSE\",\"5\":\"0\",\"6\":\"0.00000\"},{\"1\":\"239.86.201.0\",\"2\":\"TRUE\",\"3\":\"1\",\"4\":\"FALSE\",\"5\":\"1\",\"6\":\"39.45626\"},{\"1\":\"35.90.22.130\",\"2\":\"TRUE\",\"3\":\"1\",\"4\":\"FALSE\",\"5\":\"0\",\"6\":\"0.00000\"},{\"1\":\"219.176.193.3\",\"2\":\"FALSE\",\"3\":\"4\",\"4\":\"TRUE\",\"5\":\"0\",\"6\":\"0.00000\"},{\"1\":\"247.85.168.16\",\"2\":\"TRUE\",\"3\":\"1\",\"4\":\"FALSE\",\"5\":\"0\",\"6\":\"0.00000\"},{\"1\":\"120.221.249.244\",\"2\":\"TRUE\",\"3\":\"2\",\"4\":\"FALSE\",\"5\":\"0\",\"6\":\"0.00000\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n#### **Plot independent and and dependent difference**\n\n----\n\n::: {.cell hash='06_rct_cache/html/unnamed-chunk-3_dd6a91b4dc9397bb5eae662a29317a32'}\n\n```{.r .cell-code}\n# purchase_amount (dependent)\n\npurchase_amount_comp <- \n  ggplot(df, \n         aes(x = chatbot, \n             y = purchase_amount, \n             color = as.factor(chatbot))) +\n  stat_summary(geom = \"errorbar\", \n               width = .5,\n               fun.data = \"mean_se\", \n               fun.args = list(mult=1.96),\n               show.legend = F) +\n  labs(x = NULL, y = \"purchase_amount\", title = \"Difference in purchase amount\")+\n  scale_x_discrete(labels = c(\"Not Treated\",\"Treated\"))\n\n\n# previous_visit (independent)\n\nprevious_visit_comp <- \n  ggplot(df, \n         aes(x = chatbot, \n             y = previous_visit, \n             color = as.factor(chatbot))) +\n  stat_summary(geom = \"errorbar\", \n               width = .5,\n               fun.data = \"mean_se\", \n               fun.args = list(mult=1.96),\n               show.legend = F) +\n  labs(x = NULL, y = \"previous_visit\", title = \"Difference in previous visit\")+\n  scale_x_discrete(labels = c(\"Not Treated\",\"Treated\"))\n\n\n# mobile_device (independent)\nmobile_device_comp <- \n  ggplot(df, \n         aes(x = chatbot, \n             y = mobile_device, \n             color = as.factor(chatbot))) +\n  stat_summary(geom = \"errorbar\", \n               width = .5,\n               fun.data = \"mean_se\", \n               fun.args = list(mult=1.96),\n               show.legend = F) +\n  labs(x = NULL, y = \"mobile_device\", title = \"Difference in mobile device\")+\n  scale_x_discrete(labels = c(\"Not Treated\",\"Treated\"))\n\n# purchase (dependent)\n\npurchase_comp <- \n  ggplot(df, \n         aes(x = chatbot,\n             y = purchase, \n             color = as.factor(chatbot))) +\n  stat_summary(geom = \"errorbar\", \n               width = .5,\n               fun.data = \"mean_se\", \n               fun.args = list(mult=1.96),\n               show.legend = F) +\n  labs(x = NULL, y = \"purchase\", title = \"Difference in purchase\")+\n  scale_x_discrete(labels = c(\"Not Treated\",\"Treated\"))\n\n# Plot the Comparisons\n\npurchase_amount_comp\n```\n\n::: {.cell-output-display}\n![](06_rct_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n\n```{.r .cell-code}\nprevious_visit_comp\n```\n\n::: {.cell-output-display}\n![](06_rct_files/figure-html/unnamed-chunk-3-2.png){width=672}\n:::\n\n```{.r .cell-code}\nmobile_device_comp\n```\n\n::: {.cell-output-display}\n![](06_rct_files/figure-html/unnamed-chunk-3-3.png){width=672}\n:::\n\n```{.r .cell-code}\npurchase_comp\n```\n\n::: {.cell-output-display}\n![](06_rct_files/figure-html/unnamed-chunk-3-4.png){width=672}\n:::\n:::\n\n\n#### **Linear Regression to find the effect of `chatbot` on `sales`**\n\n----\n\n\n::: {.cell hash='06_rct_cache/html/unnamed-chunk-4_7304fec3f8fd6b4a4006a7a14523fd54'}\n\n```{.r .cell-code}\nmodel1 <- lm(purchase ~ chatbot, data = df)\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = purchase ~ chatbot, data = df)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -0.4960 -0.3249 -0.2679  0.5040  0.7321 \n#> \n#> Coefficients:\n#>             Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)  0.49597    0.02122  23.376  < 2e-16 ***\n#> chatbotTRUE -0.22811    0.02989  -7.633 5.36e-14 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 0.4725 on 998 degrees of freedom\n#> Multiple R-squared:  0.05516,\tAdjusted R-squared:  0.05421 \n#> F-statistic: 58.26 on 1 and 998 DF,  p-value: 5.36e-14\n```\n:::\n\n```{.r .cell-code}\nmodel2 <- lm(purchase_amount ~ chatbot, data = df)\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = purchase_amount ~ chatbot, data = df)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -16.702 -14.478  -9.626  13.922  64.648 \n#> \n#> Coefficients:\n#>             Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)  16.7017     0.8374  19.944  < 2e-16 ***\n#> chatbotTRUE  -7.0756     1.1796  -5.998 2.79e-09 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 18.65 on 998 degrees of freedom\n#> Multiple R-squared:  0.0348,\tAdjusted R-squared:  0.03383 \n#> F-statistic: 35.98 on 1 and 998 DF,  p-value: 2.787e-09\n```\n:::\n:::\n\n\n\n#### **Compute CATE for `mobile_device`**\n\n----\n\n::: {.cell hash='06_rct_cache/html/unnamed-chunk-5_e8513cb63f89666668aa7c685abca294'}\n\n```{.r .cell-code}\nmodel3 <- lm(purchase ~ chatbot * mobile_device, data = df)\nsummary(model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = purchase ~ chatbot * mobile_device, data = df)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -0.5000 -0.3284 -0.2635  0.5000  0.7484 \n#> \n#> Coefficients:\n#>                               Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)                    0.50000    0.02572  19.438  < 2e-16 ***\n#> chatbotTRUE                   -0.22464    0.03619  -6.207 7.93e-10 ***\n#> mobile_deviceTRUE             -0.01266    0.04558  -0.278    0.781    \n#> chatbotTRUE:mobile_deviceTRUE -0.01113    0.06428  -0.173    0.863    \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 0.4729 on 996 degrees of freedom\n#> Multiple R-squared:  0.05549,\tAdjusted R-squared:  0.05264 \n#> F-statistic:  19.5 on 3 and 996 DF,  p-value: 2.714e-12\n```\n:::\n\n```{.r .cell-code}\nmodel4 <- lm(purchase_amount ~ chatbot * mobile_device, data = df)\nsummary(model4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = purchase_amount ~ chatbot * mobile_device, data = df)\n#> \n#> Residuals:\n#>    Min     1Q Median     3Q    Max \n#> -16.98 -14.54  -9.95  14.13  65.24 \n#> \n#> Coefficients:\n#>                               Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)                    16.9797     1.0152  16.725   <2e-16 ***\n#> chatbotTRUE                    -7.0301     1.4284  -4.922    1e-06 ***\n#> mobile_deviceTRUE              -0.8727     1.7987  -0.485    0.628    \n#> chatbotTRUE:mobile_deviceTRUE  -0.1526     2.5369  -0.060    0.952    \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 18.66 on 996 degrees of freedom\n#> Multiple R-squared:  0.03534,\tAdjusted R-squared:  0.03244 \n#> F-statistic: 12.16 on 3 and 996 DF,  p-value: 8.034e-08\n```\n:::\n:::\n\n\n\n#### **Logistic regression model**\n\n----\n\n::: {.cell hash='06_rct_cache/html/unnamed-chunk-6_56b48604ea8b819c52692d261cb7538c'}\n\n```{.r .cell-code}\nlog_model <- glm(purchase ~ chatbot, family = binomial(link = 'logit'), data = df)\n\nsummary(log_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> glm(formula = purchase ~ chatbot, family = binomial(link = \"logit\"), \n#>     data = df)\n#> \n#> Coefficients:\n#>             Estimate Std. Error z value Pr(>|z|)    \n#> (Intercept) -0.01613    0.08981  -0.180    0.857    \n#> chatbotTRUE -0.98939    0.13484  -7.337 2.18e-13 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> (Dispersion parameter for binomial family taken to be 1)\n#> \n#>     Null deviance: 1329.1  on 999  degrees of freedom\n#> Residual deviance: 1273.3  on 998  degrees of freedom\n#> AIC: 1277.3\n#> \n#> Number of Fisher Scoring iterations: 4\n```\n:::\n:::\n\n\n::: {.callout-important appearance=\"minimal\"}\n\n-   **The chatbot_true coefficient is very intriguing. Because it has a negative estimate, it implies that the existence of the `chatbot` is related with a drop in the log-odds of making a purchase as compared to when the `chatbot` is not present.**\n\n-   **The fact that the p-value is less than 0.001 implies that the effect is statistically significant. In simpler terms, the model implies that when the `chatbot` is there, consumers are less likely to make a purchase, and this effect is unlikely to be attributable to chance.**\n\n-   **Model fit statistics include the null and residual deviance as well as the AIC (Akaike Information Criterion).**\n\n-   **In general, lower AIC values suggest better-fitting models. The residual deviation is `1273.3` on `998` degrees of freedom in this situation, and the AIC is `1277.3`**.\n\n:::",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}