{
  "hash": "7638580bbc26db735920d96e437d6ee4",
  "result": {
    "markdown": "---\ntitle: \"Instrumental Variables\"\nauthor: \"Yazan Dabbas\"\ndate: \"12/25/2023\"\nformat: \n    html:\n      code-line-numbers: true\n      df-print: paged\n---\n\n::: {.cell hash='09_iv_cache/html/unnamed-chunk-1_507c9de7b92f79110fce86050e49c63a'}\n\n```{.r .cell-code}\n# Load required libraries\nlibrary(tidyverse)\nlibrary(dagitty)\nlibrary(ggdag)\nlibrary(estimatr)\nlibrary(AER)\n```\n:::\n\n\n**First Question: **\n\n------------------------------------------------------------------------\n\n\n::: {.cell hash='09_iv_cache/html/unnamed-chunk-2_3f301ff7a6b1fb409c1a1725eab25a71'}\n\n```{.r .cell-code}\n# Define the DAG\ndag <- dagify(\n  spentTime ~ featureUsed,\n  spentTime ~ Unobserved,\n  featureUsed ~ Unobserved,\n  featureUsed ~ encourgement,\n  exposure = \"featureUsed\",\n  latent = \"Unobserved\",\n  outcome = \"spentTime\",\n  coords = list(x = c(Unobserved = 1, featureUsed = 0, spentTime = 2, encourgement = -1),\n                y = c(Unobserved = 1, featureUsed = 0, spentTime = 0, encourgement = 0)),\n  labels = c(\n    \"spentTime\" = \"Time Spent on the App\",\n    \"featureUsed\" = \"The new feature is used\",\n    \"encourgement\" = \"User encourgement to use feature\",\n    \"Unobserved\" = \"Unobserved variables\"\n  )\n)\n# Plot DAG\nggdag(dag, text = FALSE, use_labels = \"label\")\n```\n\n::: {.cell-output-display}\n![](09_iv_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n::: {.cell hash='09_iv_cache/html/unnamed-chunk-3_8ded17139306cc5cb6ffc67bbbaa0f4f'}\n\n```{.r .cell-code}\n#Load the data\ndf <- readRDS('C:/Master Degree/Core Qualification_Compulsory Courses/Business/Causal_Data_Science/Data/Causal_Data_Science_Data/rand_enc.rds')\n\n\n# Be familiar with the data\n\nhead(df)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"rand_enc\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"used_ftr\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"time_spent\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"0\",\"2\":\"1\",\"3\":\"30.51346\"},{\"1\":\"0\",\"2\":\"0\",\"3\":\"19.78372\"},{\"1\":\"1\",\"2\":\"1\",\"3\":\"28.59107\"},{\"1\":\"0\",\"2\":\"0\",\"3\":\"18.63635\"},{\"1\":\"0\",\"2\":\"0\",\"3\":\"14.55074\"},{\"1\":\"1\",\"2\":\"0\",\"3\":\"12.41954\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n**Second Question: **\n\n------------------------------------------------------------------------\n\n\n::: {.cell hash='09_iv_cache/html/unnamed-chunk-4_dff74a259ae78955c1e781ecb2c9a982'}\n\n```{.r .cell-code}\n# Compute Naive Estimate\nnaive_estimate <- lm(time_spent ~ used_ftr, data = df)\n\nsummary(naive_estimate)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = time_spent ~ used_ftr, data = df)\n#> \n#> Residuals:\n#>      Min       1Q   Median       3Q      Max \n#> -20.4950  -3.5393   0.0158   3.5961  20.5051 \n#> \n#> Coefficients:\n#>             Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept) 18.86993    0.06955   271.3   <2e-16 ***\n#> used_ftr    10.82269    0.10888    99.4   <2e-16 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 5.351 on 9998 degrees of freedom\n#> Multiple R-squared:  0.497,\tAdjusted R-squared:  0.497 \n#> F-statistic:  9881 on 1 and 9998 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n**Third Question: **\n\n------------------------------------------------------------------------\n\n::: {.cell hash='09_iv_cache/html/unnamed-chunk-5_e3415728c90878087aa92cc177a32f42'}\n\n```{.r .cell-code}\n# Check the correlation matrix\ncor(df) %>% round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#>            rand_enc used_ftr time_spent\n#> rand_enc       1.00     0.20       0.13\n#> used_ftr       0.20     1.00       0.71\n#> time_spent     0.13     0.71       1.00\n```\n:::\n:::\n\n  \n::: {.callout-important appearance=\"minimal\"} \n\n-   **Since the naive estimate (10.82269) is greater than the IV robust estimate using rand_enc as an instrument (9.738175), we would consider the naive estimate to have an upward bias.**\n\n-   **This implies that the naive estimate overestimates the effect of `used_ftr` on `time_spent`.**\n  \n-   **A strong correlation between `used_ftr` and `time_spent` can be seen.**\n\n-   **Assuming `rand_enc` as an Instrumental variable would make sense, because it has a weak correlation with the outcome `(time_spent)` and a stronger one with the treatment `(used_ftr)`.**\n\n-   **While the correlation between Instrumental variable and outcome is not  zero (maybe due to noise), this correlation is relatively low.**\n\n:::\n\n\n**Fourth Question: **\n\n------------------------------------------------------------------------\n\n::: {.cell hash='09_iv_cache/html/unnamed-chunk-6_c5b33216e5d9eba16175663c798efa44'}\n\n```{.r .cell-code}\n# Instrumental Variable Estimation using 2SLS with rand_enc and robust standard errors\n\nmodel_iv_robust <- iv_robust(time_spent ~ used_ftr | rand_enc, data = df)\nsummary(model_iv_robust)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> iv_robust(formula = time_spent ~ used_ftr | rand_enc, data = df)\n#> \n#> Standard error type:  HC2 \n#> \n#> Coefficients:\n#>             Estimate Std. Error t value  Pr(>|t|) CI Lower CI Upper   DF\n#> (Intercept)   19.312     0.2248   85.89 0.000e+00   18.872    19.75 9998\n#> used_ftr       9.738     0.5353   18.19 8.716e-73    8.689    10.79 9998\n#> \n#> Multiple R-squared:  0.4921 ,\tAdjusted R-squared:  0.492 \n#> F-statistic:   331 on 1 and 9998 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n## Hansen J test\n\n# Extract residuals and fitted values from the model\nresiduals_iv <- residuals(model_iv_robust)\nfitted_values_iv <- fitted(model_iv_robust)\n\n# Perform Hansen J test\nhansen_test_stat <- sum(residuals_iv * fitted_values_iv)\np_value_hansen <- 1 - pchisq(hansen_test_stat, df = 1)\n\n# Display results\ncat(\"Hansen J Test Statistic:\", hansen_test_stat, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> Hansen J Test Statistic: 0\n```\n:::\n\n```{.r .cell-code}\ncat(\"P-value:\", p_value_hansen, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> P-value: 1\n```\n:::\n:::\n\n\n::: {.callout-important appearance=\"minimal\"}\n\n-   **Hansen J test with a test statistic close to 0 and a p-value close to 1 indicates that the instrument used in the model is not violating the over-identifying restrictions.**\n\n-   **In other words, the instrument is valid for the model, and there is no evidence to suggest that the instrument is endogenous or correlated with the error term.** \n  \n:::\n\n\n::: {.cell hash='09_iv_cache/html/unnamed-chunk-7_ea90a2149acbb3d675991db469142fab'}\n\n```{.r .cell-code}\ncat(\"Naive Estimate:\", coef(naive_estimate)['used_ftr'], \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> Naive Estimate: 10.82269\n```\n:::\n\n```{.r .cell-code}\ncat(\"IV Robust Estimate (rand_enc):\", model_iv_robust$coefficients['used_ftr'], \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> IV Robust Estimate (rand_enc): 9.738175\n```\n:::\n:::\n\n\n::: {.callout-important appearance=\"minimal\"}\n\n-   **Since the naive estimate (10.82269) is greater than the IV robust estimate using rand_enc as an instrument (9.738175), we would consider the naive estimate to have an upward bias.**\n\n-   **This implies that the naive estimate overestimates the effect of used_ftr on time_spent.**\n  \n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}